name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - jupyterlab~=3.5.1
  - jupyterlab-drawio
  - # jupyterlab-language-pack-fr-FR
  - # jupyterlab-language-pack-zh-CN
  - jupyterlab-fasta>=3,<4
  - jupyterlab-geojson>=3,<4
  - jupyterlab-tour
  - jupyterlab_miami_nights
  - jupyterlite-core>=0.2.0
  - # jupyterlite-pyodide-kernel
  - jupyterlite-xeus-python
  - plotly>=5,<6
  - theme-darcula
  - numpy
  - pandas
  - pydantic
  - appdirs
  - scikit-learn
  - SQLAlchemy